[tools]
babashka = "latest"
claude = "latest"
clojure = "latest"
cmake = "latest"
fx = "latest"
node = "latest"
rust = "latest"
zellij = "latest"
"cargo:atuin" = "latest"
"cargo:serie" = "latest"
"cargo:stylua" = "latest"
"npm:@bitwarden/cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:@vscode/vsce" = "latest"
"ubi:borkdude/jet" = "latest"
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
