[tools]
babashka = "latest"
claude = "latest"
clojure = "latest"
cmake = "latest"
fx = "latest"
node = "24"
rust = "latest"
zellij = "latest"
"cargo:atuin" = "latest"
"cargo:serie" = "latest"
"cargo:stylua" = "latest"
"npm:@bitwarden/cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:@vscode/vsce" = "latest"
"ubi:borkdude/jet" = "latest"
usage = "latest"
"github:simulot/immich-go" = "latest"
fzf = "latest"
ripgrep = "latest"
"github:cli/cli" = "latest"
java = "24"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true
